---
title: recaptcha
description: recaptcha
url: https://enricocaputo.github.io/recaptcha
baseurl:
repository: https://enricocaputo.github.io/recaptcha
timezone: Europe/Rome
encoding: UTF-8
lang: it-IT
name: "recaptcha"

permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

markdown: kramdown

social_icons:
  - Facebook
  - Twitter
  - RSS
exclude:
  - ".gitignore"
  - CNAME
  - README.md

  # Compress
sass:
    style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  startings: [head, body]
